
after-login-command = []

after-startup-command = []

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 0

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = false

[key-mapping]
preset = 'qwerty'


[gaps]
inner.horizontal = 5
inner.vertical =   5
outer.left =       5
outer.bottom =     5
outer.top =        5
outer.right =      5


[mode.main.binding]

ctrl-comma = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'

alt-m = 'fullscreen'
alt-q = 'close'
alt-shift-r = 'reload-config'
alt-shift-space = 'macos-native-fullscreen'
alt-n = 'focus-back-and-forth'
alt-enter = 'layout floating tiling'
alt-b = 'balance-sizes'
alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-ctrl-h = 'focus-monitor left'
alt-ctrl-j = 'focus-monitor down'
alt-ctrl-k = 'focus-monitor up'
alt-ctrl-l = 'focus-monitor right'

alt-ctrl-shift-h = 'move-node-to-monitor left'
alt-ctrl-shift-j = 'move-node-to-monitor down'
alt-ctrl-shift-k = 'move-node-to-monitor up'
alt-ctrl-shift-l = 'move-node-to-monitor right'

### MODES ###
alt-r = 'mode resize'
alt-s = 'mode service'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
shift-h = 'resize width -150'
shift-j = 'resize height +150'
shift-k = 'resize height -150'
shift-l = 'resize width +150'
enter = 'mode main'
esc = 'mode main'


[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']


[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'main'
3 = ['3', 'secondary', 'main']
4 = 'main'
5 = 'main'
6 = 'main'
7 = 'main'
8 = 'main'
9 = ['1', 'secondary', 'main']


### APP BEHAVIOR ###

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = "layout floating"

[[on-window-detected]]
if.app-id = 'com.1password.1password'
run = "layout floating"

[[on-window-detected]]
if.app-id = 'com.bitwarden.desktop'
run = "layout floating"

[[on-window-detected]]
if.app-id = 'com.alienator88.Pearcleaner'
run = "layout floating"

[[on-window-detected]]
if.app-id = 'com.usebruno.app'
run = "layout floating"

[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = "move-node-to-workspace 1"
[[on-window-detected]]
if.app-id = "com.mitchellh.ghostty"
run = [
  # FIX: this is a workaround for https://github.com/nikitabobko/AeroSpace/issues/68
  # this was also observed in:
  # - https://github.com/ghostty-org/ghostty/issues/1840
  # - https://github.com/ghostty-org/ghostty/issues/2006
  "layout floating",
  "move-node-to-workspace 2",
]
[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
run = "move-node-to-workspace 3"
[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij.ce'
run = "move-node-to-workspace 3"
[[on-window-detected]]
if.app-id = 'dev.zed.Zed'
run = "move-node-to-workspace 4"
